// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ArticleTags  string
	Articles     string
	Auths        string
	ReadArticles string
	Users        string
}{
	ArticleTags:  "article_tags",
	Articles:     "articles",
	Auths:        "auths",
	ReadArticles: "read_articles",
	Users:        "users",
}
